### ISSUE TITLE
Author Page

### ISSUE THREAD

**Issue by r3volution11** [insidegui/Sharecuts#16]
Clicking on an authors name on a card (or in a "detailed view") would go to an author bio page where all shortcuts created by that author are shown. Additionally a brief bio, twitter, github, and/or website URLs if the author chooses to provide them.

**Comment by insidegui** [comment]
Agreed

**Comment by insidegui** [comment]
Implemented in Indigo, still not displaying avatar or website URL, but it's a good start.
