### ISSUE TITLE
Implement new design

### ISSUE THREAD

**Issue by insidegui** [insidegui/Sharecuts#19]
We have a new design for the frontend, it needs to be implemented in HTML/CSS. This can be done as a separate thing so the implementer doesn't need to worry about leaf or any of the features we don't have on the backend yet.

**Comment by falcon-head** [comment]
Guys whats the status here? 
Is anyone working on it?

**Comment by falcon-head** [comment]
Cool!

**Comment by insidegui** [comment]
Implemented in Indigo
