### ISSUE TITLE
Workflow & Siri Shortcuts

### ISSUE THREAD

**Issue by rparanson** [insidegui/Sharecuts#22]
Hi there.  Thank you for creating this platform.  I use workflow (no invite to Shortcuts yet) and am having a problem downloading the shortcuts on your site on iOS Safari.  The message is "Safari cannot open the page because the address is invalid."  I was hoping the link would trigger an open in Workflow for the time being.  Please advise and thanks. - Rick

**Comment by insidegui** [comment]
We do not support Workflow on the website and we don't plan on doing so given that Shortcuts is coming out in September and Workflow is going away.

**Comment by rparanson** [comment]
I understand.  Just FYI replaced "shortcuts" with "worlkflow" in your linked url scheme and the linked opened and worked fine in WorkFlow.  

shortcuts://import-workflow?url=https://sharecuts.app/download/...
replaced with
workflow://import-workflow?url=https://sharecuts.app/download/...

**Comment by insidegui** [comment]
That's a good workaround 😉
