### ISSUE TITLE
Cannot open any tips for details

### ISSUE THREAD

**Issue by KaylonNC** [insidegui/Sharecuts#27]
When selecting any of the tips, I get the error that "Safari cannot open the page because the address is invalid"

I tried every one and the outcome was the same. I also tried to copy the link and paste it in a new window. Still got same error message

**Comment by shadowfacts** [comment]
Right now shortcuts on the home page link into the Shortcuts app itself, allowing you to import them on a device running the app. 

A page with more details for each Shortcut is planned.

**Comment by insidegui** [comment]
What @shadowfacts said 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
