### ISSUE TITLE
Shortcuts unavailable 

### ISSUE THREAD

**Issue by brianoxley** [insidegui/Sharecuts#29]
Hi - I keep receiving this error message. Any help? Thanks, Brian 

![c530eee2-dc34-4f41-923e-296ea565023b](https://user-images.githubusercontent.com/42421253/44172758-fe510180-a0d5-11e8-80d9-37e240b5182a.png)

**Comment by insidegui** [comment]
Do you have the Shortcuts app installed?

**Comment by brianoxley** [comment]
Sadly no - I’m not a developer

**Comment by insidegui** [comment]
You need the Shortcuts app installed to be able to open the Shortcuts.
