### ISSUE TITLE
Add support for categories and/or tags

### ISSUE THREAD

**Issue by insidegui** [insidegui/Sharecuts#3]
Categorizing shortcuts would make them easier to find.

**Comment by marcocapano** [comment]
May I ask the state of it? Is someone working already on it or may I help?

**Comment by insidegui** [comment]
I’m on it. Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by insidegui** [comment]
Implemented in Indigo.
