### ISSUE TITLE
Add media grabber (youtube video downloader)

### ISSUE THREAD

**Issue by phelma** [insidegui/Sharecuts#31]
This workflow / shortcut downloads youtube (and other) videos.
It can be found at https://github.com/MediaGrabber/iOS-Workflow

**Comment by insidegui** [comment]
Hi @phelma ! Thanks for your contribution. This repository is for issues related to the development of the Sharecuts platform, not suggestions of shortcuts to be published. For that, we'll be opening up submissions soon.
