### ISSUE TITLE
Add upvoting and download count features

### ISSUE THREAD

**Issue by insidegui** [insidegui/Sharecuts#4]
Having a way for users to upvote shortcuts and know the ones that have been downloaded the most will allow us to add UI features that make it easier for users to find the most interesting shortcuts.

**Comment by r3volution11** [comment]
Should the number of upvotes be shown to users? What about simply basing this on the amount of downloads a shortcut has instead?

**Comment by banana-ben** [comment]
@r3volution you don’t necessarily know that a shortcut sucks or is broken until after you download it

**Comment by r3volution11** [comment]
@banana-ben Great point! I guess an option to list sharecuts from most downloaded to nothing still may be helpful. Especially when people can see how many Likes they have.

**Comment by banana-ben** [comment]
I wonder if having downvotes would be important too. I think the biggest use case for downvotes is if a shortcut becomes out of date (like if a shortcut accesses an API that has changed/disappeared). I guess it would depend of how big of a deal you think that ^ scenario is.

**Comment by r3volution11** [comment]
@banana-ben I think that's something that should be done on the backend. Downvotes are just so susceptible to bias, spam, etc.

**Comment by shadowfacts** [comment]
One thing to consider is if we want a simple voting system or something more complex.

One sites with simple votes (e.g. up/downvotes on Reddit, likes on Twitter/FB), the posts that tend to succeed are ones that evoke a reaction, such as memes and jokes. 

Fun shortcuts are certainly welcome, but given the nature of this site and of Shortcuts, we want to make sure that genuinely useful/productive shortcuts aren’t obscured by funny/jokey ones.

I’m not sure what form voting should take, but that’s my concern with a plain up/downvote style system.

**Comment by r3volution11** [comment]
I think simple upvoting will work. Once integrating with categories users will have the ability to refine their browsing to a specific category.

**Comment by r3volution11** [comment]
That's definitely being worked on. 💯

**Comment by insidegui** [comment]
Upvoting has been implemented in Indigo, download count will be implemented on the backend, should be a separate issue for frontend.
